import { Service } from './types';

export const services: Service[] = [
  {
    id: 'instagram',
    name: 'Instagram',
    slug: 'instagram',
    icon: '📷',
    description: 'Followers, likes, comments & reels.',
    isPrimary: true,
    bgGradient: 'from-pink-500 via-rose-500 to-purple-600',
    accentColor: 'bg-gradient-to-r from-pink-500 to-purple-600 hover:from-pink-600 hover:to-purple-700',
    accentText: 'text-pink-600',
    accentBgLight: 'bg-pink-50',
    packages: [
      // Followers
      {
        id: 'ig-50f',
        quantity: 50,
        quantityLabel: '50 Followers',
        price: 8,
        description: 'Mixed High Quality Followers',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-100f',
        quantity: 100,
        quantityLabel: '100 Followers',
        price: 13,
        description: 'Mixed High Quality Followers',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'followers',
        ssmServiceId: 1,
      },
      {
        id: 'ig-1000f',
        quantity: 1000,
        quantityLabel: '1000 Followers',
        price: 49,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '3-7 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-2000f',
        quantity: 2000,
        quantityLabel: '2000 Followers',
        price: 79,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-5000f',
        quantity: 5000,
        quantityLabel: '5000 Followers',
        price: 99,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '7-14 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-10000f',
        quantity: 10000,
        quantityLabel: '10000 Followers',
        price: 150,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '10-20 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-15000f',
        quantity: 15000,
        quantityLabel: '15000 Followers',
        price: 199,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '14-25 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-25000f',
        quantity: 25000,
        quantityLabel: '25000 Followers',
        price: 299,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '15-30 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-50000f',
        quantity: 50000,
        quantityLabel: '50000 Followers',
        price: 449,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '20-40 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 3822,
      },
      {
        id: 'ig-100kf',
        quantity: 100000,
        quantityLabel: '100K Followers',
        price: 649,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '30-60 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 2,
        isBestSeller: true,
      },
      {
        id: 'ig-1mf',
        quantity: 1000000,
        quantityLabel: '1M Followers',
        price: 499,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '60-90 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
        ssmServiceId: 2,
      },
      // Likes
      {
        id: 'ig-1000l',
        quantity: 1000,
        quantityLabel: '1000 Likes',
        price: 30,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '1-2 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3924,
      },
      {
        id: 'ig-2000l',
        quantity: 2000,
        quantityLabel: '2000 Likes',
        price: 48,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '2-3 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3924,
      },
      {
        id: 'ig-5000l',
        quantity: 5000,
        quantityLabel: '5000 Likes',
        price: 69,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '3-5 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3924,
      },
      {
        id: 'ig-10000l',
        quantity: 10000,
        quantityLabel: '10000 Likes',
        price: 99,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '4-7 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3924,
      },
      {
        id: 'ig-20000l',
        quantity: 20000,
        quantityLabel: '20000 Likes',
        price: 149,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
        ssmServiceId: 3,
      },
      // Comments
      {
        id: 'ig-100c',
        quantity: 100,
        quantityLabel: '100 Comments',
        price: 35,
        description: 'Indian Girls & Boys Mixed.',
        deliveryTime: '2-5 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
        ssmServiceId: 670,
      },
      {
        id: 'ig-200c',
        quantity: 200,
        quantityLabel: '200 Comments',
        price: 65,
        description: 'Indian Girls & Boys Mixed.',
        deliveryTime: '3-6 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
        ssmServiceId: 670,
      },
      {
        id: 'ig-500c',
        quantity: 500,
        quantityLabel: '500 Comments',
        price: 150,
        description: 'Indian Girls & Boys Mixed.',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
        ssmServiceId: 670,
      },
      {
        id: 'ig-1000c',
        quantity: 1000,
        quantityLabel: '1000 Comments',
        price: 280,
        description: 'Indian Girls & Boys Mixed.',
        deliveryTime: '7-14 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
        ssmServiceId: 4,
      },
      // Reel Views
      {
        id: 'ig-5000rv',
        quantity: 5000,
        quantityLabel: '5000 Reel Views',
        price: 7,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-10000rv',
        quantity: 10000,
        quantityLabel: '10000 Reel Views',
        price: 12,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-25000rv',
        quantity: 25000,
        quantityLabel: '25000 Reel Views',
        price: 25,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '2-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-50000rv',
        quantity: 50000,
        quantityLabel: '50000 Reel Views',
        price: 45,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-100000rv',
        quantity: 100000,
        quantityLabel: '100000 Reel Views',
        price: 75,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '3-5 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-200000rv',
        quantity: 200000,
        quantityLabel: '200000 Reel Views',
        price: 90,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '4-6 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-300000rv',
        quantity: 300000,
        quantityLabel: '300000 Reel Views',
        price: 109,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '5-7 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-500000rv',
        quantity: 500000,
        quantityLabel: '500000 Reel Views',
        price: 125,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '6-10 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 602,
      },
      {
        id: 'ig-1mrv',
        quantity: 1000000,
        quantityLabel: '1000000 Reel Views',
        price: 219,
        description: 'Boost views on your Instagram reels.',
        deliveryTime: '10-15 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
        ssmServiceId: 5,
      },
      // Story Views
      {
        id: 'ig-1000sv',
        quantity: 1000,
        quantityLabel: '1000 Story Views',
        price: 24,
        description: 'Boost views on your Instagram stories.',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'story_views',
        ssmServiceId: 6,
      },
      {
        id: 'ig-2000sv',
        quantity: 2000,
        quantityLabel: '2000 Story Views',
        price: 35,
        description: 'Boost views on your Instagram stories.',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'story_views',
        ssmServiceId: 6,
      },
      {
        id: 'ig-5000sv',
        quantity: 5000,
        quantityLabel: '5000 Story Views',
        price: 45,
        description: 'Boost views on your Instagram stories.',
        deliveryTime: '2-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'story_views',
        ssmServiceId: 6,
      },
      {
        id: 'ig-10000sv',
        quantity: 10000,
        quantityLabel: '10000 Story Views',
        price: 85,
        description: 'Boost views on your Instagram stories.',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
        serviceCategory: 'story_views',
        ssmServiceId: 6,
      },
    ],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    slug: 'youtube',
    icon: '▶️',
    description: 'Subscribers, views, likes & watch time.',
    isPrimary: false,
    bgGradient: 'from-red-500 to-red-700',
    accentColor: 'bg-red-500 hover:bg-red-600',
    accentText: 'text-red-600',
    accentBgLight: 'bg-red-50',
    packages: [
      // Subscribers
      {
        id: 'yt-100ks',
        quantity: 100000,
        quantityLabel: '100K Subscribers',
        price: 299,
        description: 'Indian Real Non-drop Subscribers',
        deliveryTime: '30-60 days',
        quality: 'Real Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'yt-4kwatchtime',
        quantity: 1,
        quantityLabel: '4K Hours Watchtime + 2K Subs',
        price: 499,
        description: 'Youtube monetization special.',
        deliveryTime: '30-45 days',
        quality: 'Real Quality',
        serviceCategory: 'watchtime',
      },
      {
        id: 'yt-1000s',
        quantity: 1000,
        quantityLabel: '1000 Subscribers',
        price: 59,
        description: 'Indian Real Non-drop Subscribers',
        deliveryTime: '7-14 days',
        quality: 'Real Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'yt-2000s',
        quantity: 2000,
        quantityLabel: '2000 Subscribers',
        price: 79,
        description: 'Indian Real Non-drop Subscribers',
        deliveryTime: '10-20 days',
        quality: 'Real Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'yt-5000s',
        quantity: 5000,
        quantityLabel: '5000 Subscribers',
        price: 119,
        description: 'Indian Real Non-drop Subscribers',
        deliveryTime: '14-25 days',
        quality: 'Real Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'yt-10000s',
        quantity: 10000,
        quantityLabel: '10000 Subscribers',
        price: 199,
        description: 'Indian Real Non-drop Subscribers',
        deliveryTime: '20-35 days',
        quality: 'Real Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'yt-25000s',
        quantity: 25000,
        quantityLabel: '25000 Subscribers',
        price: 249,
        description: 'Indian Real Non-drop Subscribers',
        deliveryTime: '25-45 days',
        quality: 'Real Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'yt-50000s',
        quantity: 50000,
        quantityLabel: '50000 Subscribers',
        price: 399,
        description: 'Indian Real Non-drop Subscribers',
        deliveryTime: '30-60 days',
        quality: 'Real Quality',
        serviceCategory: 'subscribers',
      },
      // Views
      {
        id: 'yt-1000v',
        quantity: 1000,
        quantityLabel: '1000 Views',
        price: 24,
        description: 'Boost views on your YouTube videos.',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'yt-2000v',
        quantity: 2000,
        quantityLabel: '2000 Views',
        price: 39,
        description: 'Boost views on your YouTube videos.',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'yt-5000v',
        quantity: 5000,
        quantityLabel: '5000 Views',
        price: 69,
        description: 'Boost views on your YouTube videos.',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'yt-10000v',
        quantity: 10000,
        quantityLabel: '10000 Views',
        price: 99,
        description: 'Boost views on your YouTube videos.',
        deliveryTime: '3-5 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'yt-50000v',
        quantity: 50000,
        quantityLabel: '50000 Views',
        price: 199,
        description: 'Boost views on your YouTube videos.',
        deliveryTime: '5-10 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'yt-100000v',
        quantity: 100000,
        quantityLabel: '100000 Views',
        price: 299,
        description: 'Boost views on your YouTube videos.',
        deliveryTime: '7-14 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'yt-10mv',
        quantity: 10000000,
        quantityLabel: '10 Million Views',
        price: 499,
        description: 'Shorts Monetization special.',
        deliveryTime: '30-60 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      // Likes
      {
        id: 'yt-1000l',
        quantity: 1000,
        quantityLabel: '1000 Likes',
        price: 24,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '1-2 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
      },
      {
        id: 'yt-2000l',
        quantity: 2000,
        quantityLabel: '2000 Likes',
        price: 35,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '2-3 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
      },
      {
        id: 'yt-5000l',
        quantity: 5000,
        quantityLabel: '5000 Likes',
        price: 49,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '3-5 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
      },
      {
        id: 'yt-10000l',
        quantity: 10000,
        quantityLabel: '10000 Likes',
        price: 89,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '4-7 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
      },
      // Comments
      {
        id: 'yt-100c',
        quantity: 100,
        quantityLabel: '100 Comments',
        price: 35,
        description: 'Indian Real Comments',
        deliveryTime: '2-5 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
      },
      {
        id: 'yt-200c',
        quantity: 200,
        quantityLabel: '200 Comments',
        price: 65,
        description: 'Indian Real Comments',
        deliveryTime: '3-6 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
      },
      {
        id: 'yt-500c',
        quantity: 500,
        quantityLabel: '500 Comments',
        price: 150,
        description: 'Indian Real Comments',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
      },
      {
        id: 'yt-1000c',
        quantity: 1000,
        quantityLabel: '1000 Comments',
        price: 280,
        description: 'Indian Real Comments',
        deliveryTime: '7-14 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
      },
    ],
  },
  {
    id: 'facebook',
    name: 'Facebook',
    slug: 'facebook',
    icon: '👥',
    description: 'Page likes, followers, comments & more.',
    isPrimary: false,
    bgGradient: 'from-blue-500 to-blue-700',
    accentColor: 'bg-blue-500 hover:bg-blue-600',
    accentText: 'text-blue-600',
    accentBgLight: 'bg-blue-50',
    packages: [
      // Followers
      {
        id: 'fb-1000f',
        quantity: 1000,
        quantityLabel: '1000 Followers',
        price: 49,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '3-7 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
      },
      {
        id: 'fb-2000f',
        quantity: 2000,
        quantityLabel: '2000 Followers',
        price: 79,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
      },
      {
        id: 'fb-5000f',
        quantity: 5000,
        quantityLabel: '5000 Followers',
        price: 129,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '7-14 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
      },
      {
        id: 'fb-10000f',
        quantity: 10000,
        quantityLabel: '10000 Followers',
        price: 150,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '10-20 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
      },
      {
        id: 'fb-25000f',
        quantity: 25000,
        quantityLabel: '25000 Followers',
        price: 299,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '14-25 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
      },
      {
        id: 'fb-50000f',
        quantity: 50000,
        quantityLabel: '50000 Followers',
        price: 499,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '20-35 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
      },
      {
        id: 'fb-100000f',
        quantity: 100000,
        quantityLabel: '100000 Followers',
        price: 899,
        description: 'Indian Real Non-drop Followers',
        deliveryTime: '30-60 days',
        quality: 'Real Quality',
        serviceCategory: 'followers',
      },
      // Likes
      {
        id: 'fb-1000l',
        quantity: 1000,
        quantityLabel: '1000 Likes',
        price: 26,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '1-2 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
      },
      {
        id: 'fb-2000l',
        quantity: 2000,
        quantityLabel: '2000 Likes',
        price: 35,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '2-3 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
      },
      {
        id: 'fb-5000l',
        quantity: 5000,
        quantityLabel: '5000 Likes',
        price: 59,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '3-5 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
      },
      {
        id: 'fb-10000l',
        quantity: 10000,
        quantityLabel: '10000 Likes',
        price: 89,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '4-7 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
      },
      {
        id: 'fb-20000l',
        quantity: 20000,
        quantityLabel: '20000 Likes',
        price: 149,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
      },
      {
        id: 'fb-50000l',
        quantity: 50000,
        quantityLabel: '50000 Likes',
        price: 299,
        description: 'Indian Real Non-drop Likes',
        deliveryTime: '10-20 days',
        quality: 'Real Quality',
        serviceCategory: 'likes',
      },
      // Comments
      {
        id: 'fb-100c',
        quantity: 100,
        quantityLabel: '100 Comments',
        price: 29,
        description: 'Indian Real Comments',
        deliveryTime: '2-4 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
      },
      {
        id: 'fb-200c',
        quantity: 200,
        quantityLabel: '200 Comments',
        price: 55,
        description: 'Indian Real Comments',
        deliveryTime: '3-5 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
      },
      {
        id: 'fb-500c',
        quantity: 500,
        quantityLabel: '500 Comments',
        price: 120,
        description: 'Indian Real Comments',
        deliveryTime: '5-8 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
      },
      {
        id: 'fb-1000c',
        quantity: 1000,
        quantityLabel: '1000 Comments',
        price: 220,
        description: 'Indian Real Comments',
        deliveryTime: '7-12 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
      },
      {
        id: 'fb-2000c',
        quantity: 2000,
        quantityLabel: '2000 Comments',
        price: 399,
        description: 'Indian Real Comments',
        deliveryTime: '10-18 days',
        quality: 'Real Quality',
        serviceCategory: 'comments',
      },
      // Views
      {
        id: 'fb-1000v',
        quantity: 1000,
        quantityLabel: '1000 Views',
        price: 15,
        description: 'Boost views on your Facebook videos or posts.',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'fb-2000v',
        quantity: 2000,
        quantityLabel: '2000 Views',
        price: 24,
        description: 'Boost views on your Facebook videos or posts.',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'fb-5000v',
        quantity: 5000,
        quantityLabel: '5000 Views',
        price: 45,
        description: 'Boost views on your Facebook videos or posts.',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'fb-10000v',
        quantity: 10000,
        quantityLabel: '10000 Views',
        price: 75,
        description: 'Boost views on your Facebook videos or posts.',
        deliveryTime: '3-5 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'fb-50000v',
        quantity: 50000,
        quantityLabel: '50000 Views',
        price: 199,
        description: 'Boost views on your Facebook videos or posts.',
        deliveryTime: '5-10 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'fb-100000v',
        quantity: 100000,
        quantityLabel: '100000 Views',
        price: 349,
        description: 'Boost views on your Facebook videos or posts.',
        deliveryTime: '7-14 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'fb-500000v',
        quantity: 500000,
        quantityLabel: '500000 Views',
        price: 999,
        description: 'Boost views on your Facebook videos or posts.',
        deliveryTime: '20-40 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
    ],
  },
  {
    id: 'netflix',
    name: 'Netflix',
    slug: 'netflix',
    icon: '🎬',
    description: 'Watch your favorite shows.',
    isPrimary: false,
    bgGradient: 'from-red-600 to-red-900',
    accentColor: 'bg-red-600 hover:bg-red-700',
    accentText: 'text-red-700',
    accentBgLight: 'bg-red-50',
    packages: [
      {
        id: 'nf-1m-hd',
        quantity: 1,
        quantityLabel: 'Netflix 1 Month HD',
        price: 39,
        description: 'Access Netflix in HD for 1 month.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
      {
        id: 'nf-1m-std',
        quantity: 1,
        quantityLabel: 'Netflix 1 Month Standard',
        price: 49,
        description: 'Access Netflix in standard quality for 1 month.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
      {
        id: 'nf-3m-hd',
        quantity: 3,
        quantityLabel: 'Netflix 3 Months HD',
        price: 69,
        description: 'Access Netflix in HD for 3 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
      {
        id: 'nf-3m-std',
        quantity: 3,
        quantityLabel: 'Netflix 3 Months Standard',
        price: 75,
        description: 'Access Netflix in standard quality for 3 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
      {
        id: 'nf-6m-hd',
        quantity: 6,
        quantityLabel: 'Netflix 6 Months HD',
        price: 119,
        description: 'Access Netflix in HD for 6 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
      {
        id: 'nf-6m-std',
        quantity: 6,
        quantityLabel: 'Netflix 6 Months Standard',
        price: 139,
        description: 'Access Netflix in standard quality for 6 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
    ],
  },
  {
    id: 'amazon-prime',
    name: 'Amazon Prime',
    slug: 'amazon-prime',
    icon: '📦',
    description: 'Shop and stream.',
    isPrimary: false,
    bgGradient: 'from-sky-500 to-blue-700',
    accentColor: 'bg-sky-500 hover:bg-sky-600',
    accentText: 'text-sky-600',
    accentBgLight: 'bg-sky-50',
    packages: [
      {
        id: 'ap-1m',
        quantity: 1,
        quantityLabel: 'Amazon Prime 1 Month',
        price: 29,
        description: 'Access Amazon Prime benefits for 1 month.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
      {
        id: 'ap-3m',
        quantity: 3,
        quantityLabel: 'Amazon Prime 3 Months',
        price: 39,
        description: 'Access Amazon Prime benefits for 3 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
      {
        id: 'ap-6m',
        quantity: 6,
        quantityLabel: 'Amazon Prime 6 Months',
        price: 59,
        description: 'Access Amazon Prime benefits for 6 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
      {
        id: 'ap-12m',
        quantity: 12,
        quantityLabel: 'Amazon Prime 12 Months',
        price: 99,
        description: 'Access Amazon Prime benefits for 12 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
    ],
  },
  {
    id: 'spotify',
    name: 'Spotify',
    slug: 'spotify',
    icon: '🎵',
    description: 'Listen to music and podcasts.',
    isPrimary: false,
    bgGradient: 'from-green-500 to-green-700',
    accentColor: 'bg-green-500 hover:bg-green-600',
    accentText: 'text-green-600',
    accentBgLight: 'bg-green-50',
    packages: [
      {
        id: 'sp-3m',
        quantity: 3,
        quantityLabel: 'Spotify 3 Months Premium',
        price: 26,
        description: 'Access Spotify Premium for 3 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
      {
        id: 'sp-6m',
        quantity: 6,
        quantityLabel: 'Spotify 6 Months Premium',
        price: 49,
        description: 'Access Spotify Premium for 6 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
      {
        id: 'sp-12m',
        quantity: 12,
        quantityLabel: 'Spotify 12 Months Premium',
        price: 65,
        description: 'Access Spotify Premium for 12 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'subscription',
      },
    ],
  },
  {
    id: 'telegram',
    name: 'Telegram',
    slug: 'telegram',
    icon: '✈️',
    description: 'Grow your Telegram presence with targeted services.',
    isPrimary: false,
    bgGradient: 'from-sky-400 to-cyan-600',
    accentColor: 'bg-sky-500 hover:bg-sky-600',
    accentText: 'text-sky-600',
    accentBgLight: 'bg-sky-50',
    packages: [
      // Premium
      {
        id: 'tg-premium-1m',
        quantity: 1,
        quantityLabel: 'Telegram Premium 1 Month',
        price: 99,
        description: 'Telegram Premium subscription for 1 month.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'premium',
      },
      {
        id: 'tg-premium-3m',
        quantity: 3,
        quantityLabel: 'Telegram Premium 3 Months',
        price: 249,
        description: 'Telegram Premium subscription for 3 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'premium',
      },
      {
        id: 'tg-premium-6m',
        quantity: 6,
        quantityLabel: 'Telegram Premium 6 Months',
        price: 449,
        description: 'Telegram Premium subscription for 6 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'premium',
      },
      {
        id: 'tg-premium-12m',
        quantity: 12,
        quantityLabel: 'Telegram Premium 12 Months',
        price: 799,
        description: 'Telegram Premium subscription for 12 months.',
        deliveryTime: '1-2 hours',
        quality: 'Premium',
        serviceCategory: 'premium',
      },
      // Group Members
      {
        id: 'tg-500m',
        quantity: 500,
        quantityLabel: '500 Group Members',
        price: 49,
        description: 'Real members added to your Telegram group.',
        deliveryTime: '1-3 days',
        quality: 'Real Quality',
        serviceCategory: 'members',
      },
      {
        id: 'tg-1000m',
        quantity: 1000,
        quantityLabel: '1000 Group Members',
        price: 79,
        description: 'Real members added to your Telegram group.',
        deliveryTime: '2-5 days',
        quality: 'Real Quality',
        serviceCategory: 'members',
      },
      {
        id: 'tg-2000m',
        quantity: 2000,
        quantityLabel: '2000 Group Members',
        price: 139,
        description: 'Real members added to your Telegram group.',
        deliveryTime: '3-7 days',
        quality: 'Real Quality',
        serviceCategory: 'members',
      },
      {
        id: 'tg-5000m',
        quantity: 5000,
        quantityLabel: '5000 Group Members',
        price: 299,
        description: 'Real members added to your Telegram group.',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'members',
      },
      {
        id: 'tg-10000m',
        quantity: 10000,
        quantityLabel: '10000 Group Members',
        price: 549,
        description: 'Real members added to your Telegram group.',
        deliveryTime: '7-14 days',
        quality: 'Real Quality',
        serviceCategory: 'members',
      },
      // Channel Subscribers
      {
        id: 'tg-500sub',
        quantity: 500,
        quantityLabel: '500 Channel Subscribers',
        price: 45,
        description: 'Real subscribers added to your Telegram channel.',
        deliveryTime: '1-3 days',
        quality: 'Real Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'tg-1000sub',
        quantity: 1000,
        quantityLabel: '1000 Channel Subscribers',
        price: 79,
        description: 'Real subscribers added to your Telegram channel.',
        deliveryTime: '2-5 days',
        quality: 'Real Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'tg-2000sub',
        quantity: 2000,
        quantityLabel: '2000 Channel Subscribers',
        price: 139,
        description: 'Real subscribers added to your Telegram channel.',
        deliveryTime: '3-7 days',
        quality: 'Real Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'tg-5000sub',
        quantity: 5000,
        quantityLabel: '5000 Channel Subscribers',
        price: 289,
        description: 'Real subscribers added to your Telegram channel.',
        deliveryTime: '5-10 days',
        quality: 'Real Quality',
        serviceCategory: 'subscribers',
      },
      {
        id: 'tg-10000sub',
        quantity: 10000,
        quantityLabel: '10000 Channel Subscribers',
        price: 529,
        description: 'Real subscribers added to your Telegram channel.',
        deliveryTime: '7-14 days',
        quality: 'Real Quality',
        serviceCategory: 'subscribers',
      },
      // Post Views
      {
        id: 'tg-1000v',
        quantity: 1000,
        quantityLabel: '1000 Post Views',
        price: 19,
        description: 'Boost views on your Telegram posts.',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'tg-5000v',
        quantity: 5000,
        quantityLabel: '5000 Post Views',
        price: 49,
        description: 'Boost views on your Telegram posts.',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'tg-10000v',
        quantity: 10000,
        quantityLabel: '10000 Post Views',
        price: 89,
        description: 'Boost views on your Telegram posts.',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'tg-50000v',
        quantity: 50000,
        quantityLabel: '50000 Post Views',
        price: 199,
        description: 'Boost views on your Telegram posts.',
        deliveryTime: '3-6 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'tg-100000v',
        quantity: 100000,
        quantityLabel: '100000 Post Views',
        price: 349,
        description: 'Boost views on your Telegram posts.',
        deliveryTime: '5-8 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'tg-500000v',
        quantity: 500000,
        quantityLabel: '500000 Post Views',
        price: 999,
        description: 'Boost views on your Telegram posts.',
        deliveryTime: '10-20 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      {
        id: 'tg-1000000v',
        quantity: 1000000,
        quantityLabel: '1000000 Post Views',
        price: 1799,
        description: 'Boost views on your Telegram posts.',
        deliveryTime: '20-35 days',
        quality: 'Mixed Quality',
        serviceCategory: 'views',
      },
      // Reactions
      {
        id: 'tg-100r',
        quantity: 100,
        quantityLabel: '100 Reactions',
        price: 19,
        description: 'Boost reactions on your Telegram post.',
        deliveryTime: '1-2 days',
        quality: 'Mixed Quality',
        serviceCategory: 'reactions',
      },
      {
        id: 'tg-500r',
        quantity: 500,
        quantityLabel: '500 Reactions',
        price: 59,
        description: 'Boost reactions on your Telegram post.',
        deliveryTime: '1-3 days',
        quality: 'Mixed Quality',
        serviceCategory: 'reactions',
      },
      {
        id: 'tg-1000r',
        quantity: 1000,
        quantityLabel: '1000 Reactions',
        price: 99,
        description: 'Boost reactions on your Telegram post.',
        deliveryTime: '2-4 days',
        quality: 'Mixed Quality',
        serviceCategory: 'reactions',
      },
      {
        id: 'tg-5000r',
        quantity: 5000,
        quantityLabel: '5000 Reactions',
        price: 349,
        description: 'Boost reactions on your Telegram post.',
        deliveryTime: '3-6 days',
        quality: 'Mixed Quality',
        serviceCategory: 'reactions',
      },
      {
        id: 'tg-10000r',
        quantity: 10000,
        quantityLabel: '10000 Reactions',
        price: 649,
        description: 'Boost reactions on your Telegram post.',
        deliveryTime: '5-10 days',
        quality: 'Mixed Quality',
        serviceCategory: 'reactions',
      },
    ],
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}

export function getAllServices(): Service[] {
  return services;
}

export function getPrimaryService(): Service | undefined {
  return services.find((s) => s.isPrimary);
}
